backend fixes: unzip error catching, only mount system rw if necessary
- initial unzip verification to catch it early on broken recoveries/zips
- display the matching name during the devicecheck while installing
- mount /system ro for the off-chance getprop relies on build.prop (older recoveries),
	and only remount rw if init.d or modules need to be setup/installed to fix/workaround TWRP's
	"mount only as ro" feature being finicky and allow /system to remain untouched on devices supporting systemless root.
- add signing documentation to README

Thanks a lot @osm0sis

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -29,11 +29,14 @@ show_progress 1.34 4;
 mkdir -p /tmp/anykernel;
 cd /tmp/anykernel;
 unzip -o "$ZIP";
+if [ $? != 0 -o -z "$(ls /tmp/anykernel)" ]; then
+  abort "Unzip failed. Aborting...";
+fi;
 cp -f /tmp/anykernel/tools/getprop /sbin/;
 
 ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
 ui_print "AnyKernel2 by osm0sis @ xda-developers";
-/sbin/busybox mount /system;
+/sbin/busybox mount -o ro /system;
 /sbin/busybox mount /data;
 
 ui_print "";
@@ -52,6 +55,7 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
   for i in 1 2 3 4 5; do
     testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
     if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+      ui_print "$testname";
       match=1;
     fi;
   done;
@@ -63,12 +67,15 @@ fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
   ui_print "Creating init.d...";
+  /sbin/busybox mount -o remount,rw /system;
   mkdir /system/etc/init.d;
   set_perm_recursive 0 0 0755 0755 /system/etc/init.d;
+  /sbin/busybox mount -o remount,ro /system;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.ukm)" == 1 ]; then
   ui_print "Install ukm...";
+  /sbin/busybox mount -o remount,rw /system;
   rm -rf /data/UKM/*;
   rm -rf /system/etc/init.d/UKM;
   rm -rf /system/xbin/uci;
@@ -83,6 +90,7 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.ukm)" == 1 ]; then
   set_perm_recursive 0 0 0755 0755 /system/xbin/uci;
   set_perm_recursive 0 0 0755 0755 /system/etc/init.d/UKM;
   set_perm_recursive 0 0 0755 0755 /system/addon.d/UKM.sh;
+  /sbin/busybox mount -o remount,ro /system;
 fi;
 
 ui_print "Installing kernel...";
@@ -94,8 +102,10 @@ fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
   ui_print "Pushing modules...";
+  /sbin/busybox mount -o remount,rw /system;
   cp -f /tmp/anykernel/modules/* /system/lib/modules/;
   set_perm_recursive 0 0 0755 0644 /system/lib/modules;
+  /sbin/busybox mount -o remount,ro /system;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
